### ISSUE TITLE
CLI datasets list error `no attribute 'years'`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-core#91]
Following these instructions: https://policyengine.github.io/policyengine-core/usage/cli.html#data

```shell
(policyengine) maxghenis@MacBook-Air-3 policyengine-us % policyengine-core data datasets list -c policyengine_us
Traceback (most recent call last):
  File "/Users/maxghenis/miniconda3/envs/policyengine/bin/policyengine-core", line 8, in <module>
    sys.exit(main())
  File "/Users/maxghenis/miniconda3/envs/policyengine/lib/python3.9/site-packages/policyengine_core/scripts/policyengine_command.py", line 128, in main
    return sys.exit(main(parser))
  File "/Users/maxghenis/miniconda3/envs/policyengine/lib/python3.9/site-packages/policyengine_core/scripts/run_data.py", line 36, in main
    print(dataset_summary(datasets))
  File "/Users/maxghenis/miniconda3/envs/policyengine/lib/python3.9/site-packages/policyengine_core/scripts/run_data.py", line 12, in dataset_summary
    years = list(sorted(list(set(sum([ds.years for ds in datasets], [])))))
  File "/Users/maxghenis/miniconda3/envs/policyengine/lib/python3.9/site-packages/policyengine_core/scripts/run_data.py", line 12, in <listcomp>
    years = list(sorted(list(set(sum([ds.years for ds in datasets], [])))))
AttributeError: type object 'CPS_2020' has no attribute 'years'
```

**Comment by nikhilwoodruff** [comment]
Amending so that it produces this instead:

![image](https://github.com/PolicyEngine/policyengine-core/assets/35577657/928e138e-43b6-45bf-8c42-93f6f47e99d8)
